name: desktop
description: Build for desktop

runs:
  using: "composite"
  steps:
    - uses: ./.github/actions/rust-cache
    - name: Install Dependencies
      shell: bash
      run: sudo apt-get install -y libwayland-dev libxkbcommon-dev # Required for winit
    - name: Build
      shell: bash
      run: cargo build -p maplibre-demo
    - uses: actions/upload-artifact@v2
      with:
        name: maplibre-rs
        path: target/x86_64-unknown-linux-gnu/debug/maplibre-demo