[package]
name = "mapr"
version = "0.1.0"
authors = ["Maximilian Ammann <max@maxammann.org>"]
edition = "2021"
resolver = "2"

[features]
web-webgl = [ "wgpu/webgl" ]

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1"
winit = { version = "0.25", features = ["web-sys"] }
web-sys = "0.3"
js-sys = "0.3"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
console_log = { version = "0.2", features = ["color"] }
instant = { version = "0.1", features = [ "stdweb" ] }

[dependencies]
# Futures
futures = "0.3.5"
pollster = "0.2"

# Vector riles
vector-tile = { path = "libs/vector_tile" }
geo = "0.18.0"
geo-types = "0.7"
# proj = "0.24" FIXME: Incompatible with wasm
# mbutiles = "0.1.1" FIXME: Incompatible with wasm
cgmath = "0.18"

# Rendering
winit = { version = "0.25" }
wgpu = "0.11"
lyon = { version = "0.17", features = ["extra"] }
lyon_path = "0.17"
# https://docs.rs/euclid/0.22.6/euclid/index.html

# Logging
log = "0.4"
env_logger = "0.9"

# Utils
hexdump = "0.1"
bytemuck = "1.2.0"
bytemuck_derive = "1.0"

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[dev-dependencies]
criterion = "0.3"
# Support logging in tests
test-env-log = "0.2"

[build-dependencies]
naga = { version = "0.7", features = ["wgsl-in"] }
walkdir = "2.3"


[[bin]]
name = "mapr"
path = "src/main.rs"
