[workspace]

resolver = "2"

members = [
    "maplibre",
    "maplibre-core",
    "maplibre-android",
    "maplibre-apple",
    "maplibre-web",

    "maplibre-style",
    "maplibre-tilejson",

    "maplibre-benchmark",
    "maplibre-build-tools",

    "maplibre-example",
]

[profile.release]
lto = true
codegen-units = 1
opt-level = 's'
panic = "abort"

[profile.bench]
debug = true
