[package]
name = "mapr"
version = "0.1.0"
authors = ["Maximilian Ammann <max@maxammann.org>"]
edition = "2021"
resolver = "2"

[features]

[dependencies]

# Futures
tokio = { version = "1", features = ["full"] }
futures = "0.3.5"
pollster = "0.2"

# Wanted by lyon experiment


# Vector riles
mvt = { path = "libs/mvt" }
vector-tile = { path = "libs/vector_tile" }
geo = "0.18.0"
geo-types = "0.7"
proj = "0.24"
mbutiles = "0.1.1"

# Rendering
winit = "0.25"
wgpu = "0.11"
lyon = { version = "0.17", features = ["extra"] }
lyon_path = "0.17"
# https://docs.rs/euclid/0.22.6/euclid/index.html

# Logging
log = "0.4"
env_logger = "0.9"

# Utils
hexdump = "0.1"
bytemuck = "1.2.0"

# Network
reqwest = { version = "0.11", features = ["gzip"] }

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[dev-dependencies]
criterion = "0.3"
# Support logging in tests
test-env-log = "0.2"
env_logger = "0.8" # Used for test-env-log


[[bin]]
name = "mapr"
path = "src/main.rs"


[[bin]]
name = "lyon_test"
path = "src/lyon_test/main.rs"

[[bin]]
name = "download_tiles"
path = "src/lyon_test/tile_downloader.rs"
