[workspace]

members = [
    #"maplibre",
    "maplibre-core",
    "maplibre-android",
    "maplibre-apple",
    "maplibre-web",

    "maplibre-style",
    "maplibre-tilejson",

    "maplibre-benchmark",
    "maplibre-build-tools",

    "maplibre-example",
]
