[toolchain]
channel = "1.57"
targets = [ "wasm32-unknown-unknown", "x86_64-unknown-linux-gnu", "aarch64-linux-android" ]
components = [ "rust-src" ] # rust-src is required for WASM builds which recompile the stdlib