name: docs
description: Build documentation

runs:
  using: "composite"
  steps:
    - uses: ./.github/actions/rust-cache
    - name: Install mdbook
      shell: bash
      run: |
        cargo install mdbook --no-default-features --vers "^0.4.0"
    - name: Install Dependencies
      shell: bash
      run: sudo apt-get install -y libwayland-dev libxkbcommon-dev # Required for winit
    - name: Build
      working-directory: docs
      shell: bash
      run: mdbook build
    - name: API Documentation
      shell: bash
      run: cargo doc -p maplibre --no-deps --lib --all-features --document-private-items
