[package]
name = "maplibre-apple"
version = "0.1.0"
description = ""
categories = []
edition = "2021"

[dependencies]
maplibre = { path = "../maplibre" }
env_logger = "0.9"

[lib]
crate-type = ["staticlib"]
