name: check
description: Check

runs:
  using: "composite"
  steps:
    - name: Setup
      shell: bash
      run: |
        rustup component add rustfmt
    - name: Format
      shell: bash
      run: cargo fmt --all -- --check
    - name: Install Dependencies
      shell: bash
      run: sudo apt-get install -y libwayland-dev libxkbcommon-dev # Required for winit
    - name: Clippy
      shell: bash
      run: |
        rustup component add clippy
        cargo clippy --all-targets --all-features