name: check
description: Check

runs:
  using: "composite"
  steps:
    - uses: ./.github/actions/rust-cache
    - name: Install just
      shell: bash
      run: cargo install just
    - name: Format
      shell: bash
      run: just fmt-check
    - name: Install Dependencies
      shell: bash
      run: sudo apt-get install -y libwayland-dev libxkbcommon-dev # Required for winit
    - name: Clippy
      shell: bash
      run: just clippy