name: webgpu
description: Build for webgpu

runs:
  using: "composite"
  steps:
    - uses: extractions/setup-just@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Install nightly toolchain
      shell: bash
      run: just nightly-toolchain
    - uses: Swatinem/rust-cache@v1
    - name: Build lib
      shell: bash
      run: just web-library parcel
    - name: Build demo
      shell: bash
      run: just web-demo build
    - name: Check
      shell: bash
      run: just check web wasm32-unknown-unknown