name: webgpu
description: Build for webgpu

runs:
  using: "composite"
  steps:
    - uses: ./.github/actions/rust-cache
    - name: Install just
      shell: bash
      run: cargo install just
    - name: Build
      shell: bash
      run: just webpack-production
