name: android
description: Build for android

runs:
  using: "composite"
  steps:
    - uses: ./.github/actions/rust-cache
    - name: Install just
      shell: bash
      run: cargo install just
    - name: Build
      shell: bash
      run: just build-apk
    - uses: actions/upload-artifact@v2
      with:
        name: maplibre-rs.apk
        path: target/debug/apk/maplibre-rs-demo.apk
