name: webgl
description: Build for webgl

runs:
  using: "composite"
  steps:
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          ~/.cargo/.crates*
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Install just
      shell: bash
      run: cargo install just
    - name: Build
      shell: bash
      run: just webpack-webgl-production
