name: webgl
description: Build for webgl

runs:
  using: "composite"
  steps:
    - uses: extractions/setup-just@v1
    - name: Install nightly toolchain
      shell: bash
      run: just nightly-toolchain
    - uses: Swatinem/rust-cache@v1
      with:
        toolchain: nightly
    - name: Build
      shell: bash
      run: just webpack-webgl-production
