# The following workflows is expensive to run and runs less frequently.

name: Apple (Expensive)

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 17 * * 1'

jobs:
  build:
    runs-on: macOS-12
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2
      - uses: extractions/setup-just@v1
      - uses: actions-rs/toolchain@v1
      - uses: Swatinem/rust-cache@v1
      - name: Build xcframework
        run: just xcodebuild-xcframework
      - name: Build Example
        run: cd apple/xcode && xcodebuild -scheme "example (iOS)" -arch arm64 -sdk iphoneos build CODE_SIGNING_ALLOWED=NO
