name: check

on: [ workflow_dispatch ]

jobs:
  check-format:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Setup
        run: |
          rustup component add rustfmt
      - name: Format
        run: cargo fmt --all -- --check
      - name: Clippy
        run: |
          rustup component add clippy
          cargo clippy --all-targets --all-features