name: desktop

on: [ workflow_dispatch ]

jobs:
  build-x86:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            ~/.cargo/.crates*
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Install Dependencies
        run: sudo apt-get install -y libwayland-dev libxkbcommon-dev # Required for winit
      - name: Build
        run: cargo build --example desktop
      - uses: actions/upload-artifact@v2
        with:
          name: maplibre-rs
          path: target/debug/maplibre