name: docs

on: [ workflow_dispatch ]

jobs:
  book:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
        working-directory: docs
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            ~/.cargo/.crates*
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-1
      - name: Install mdbook
        run: |
          cargo install mdbook --no-default-features --vers "^0.4.0"
      - name: Build
        run: mdbook build
      - name: API Documentation
        run: cargo doc --no-deps --workspace --lib --all-features --document-private-items
