name: Build library for WebGPU

on:
  workflow_call:

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  library-webgpu:
    name: Build library for WebGPU
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: extractions/setup-just@v1
      - name: Install nightly toolchain
        shell: bash
        run: just nightly-toolchain
      - uses: Swatinem/rust-cache@v1
      - name: Build lib
        shell: bash
        run: just web-lib esbuild
      - name: Build demo
        shell: bash
        run: just web-demo build
      - name: Check
        shell: bash
        run: just check web wasm32-unknown-unknown
      - name: Test
        shell: bash
        run: |
          cargo install wasm-bindgen-cli --version "0.2.80"
          just web-test ""
      - uses: ./.github/actions/deploy
        with:
          source: web/demo/dist/.
          destination: webgpu
          key: ${{ secrets.SSH_KEY_MAXAMMANN_ORG }}