name: Build & Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  run-check:
    uses: ./.github/workflows/run-checks.yml
  run-benchmarks:
    uses: ./.github/workflows/run-benchmarks.yml
  run-tests:
    uses: ./.github/workflows/run-tests.yml
  build-deploy-docs:
    uses: ./.github/workflows/build-deploy-docs.yml
    with:
      deploy: true
    secrets: inherit
  library-android:
    uses: ./.github/workflows/library-android.yml
  library-webgpu:
    uses: ./.github/workflows/library-webgpu.yml
  library-webgl:
    uses: ./.github/workflows/library-webgl.yml
  library-apple:
    uses: ./.github/workflows/library-apple.yml
  build-demo-linux:
    uses: ./.github/workflows/demo-linux.yml
  build-demo-windows:
    uses: ./.github/workflows/demo-windows.yml
  build-demo-macos:
    uses: ./.github/workflows/demo-macos.yml
    secrets: inherit

