name: Rust

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-x86:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Build
        run: cargo build --bin mapr

  build-wasm:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: web
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: NPM Install
        run: npm install
      - name: Build
        run: npm run build
      - name: Prepare for deployment
        run: mv dist public
      - name: Deploy to gh-pages 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: web/public

