name: Rust

on: [ push, pull_request ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-x86:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Build
        run: cargo build --bin mapr

  build-wasm:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: web
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Prepare Rust Toolchain # This is required because we are recompiling the stdlib
        run: |
          rustup install nightly-2021-12-07-x86_64-unknown-linux-gnu
          rustup component add rust-src --toolchain nightly-2021-12-07-x86_64-unknown-linux-gnu
      - name: NPM Install
        run: npm install
      - name: Build
        run: npm run build
      - name: Prepare for deployment
        run: |
          mv dist public
          cp ../vercel.json public/
      - uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.ORG_ID}}
          vercel-project-id: ${{ secrets.PROJECT_ID}}
          working-directory: web/public
          vercel-args: '--prod'
