name: Rust

on: [ push, pull_request ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-x86:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Build
        run: cargo build --bin mapr

  build-wasm:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: web
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Prepare Rust Toolchain # This is required because we are recompiling the stdlib
        run: |
          rustup install nightly-2021-12-07-x86_64-unknown-linux-gnu
          rustup component add rust-src --toolchain nightly-2021-12-07-x86_64-unknown-linux-gnu
      - name: NPM Install
        run: npm install
      - name: Build
        run: npm run build
      - name: Deploy to maxammann.org
        env:
          SSH_KEY: ${{ secrets.SSH_KEY_MAXAMMANN_ORG }}
        run: |
          echo "$SSH_KEY" > id_rsa
          chmod 600 id_rsa
          ssh -o StrictHostKeyChecking=no -i id_rsa max@maxammann.org "rm -f ~/public_html/mapr/*"
          rsync -e "ssh -o StrictHostKeyChecking=no -i id_rsa" -r "dist/." max@maxammann.org:~/public_html/mapr/

  book:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: docs
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Install mdbook
        run: |
          cargo install mdbook --no-default-features --features output --vers "^0.1.0"
      - name: Build
        run: mdbook build
      - name: Deploy to maxammann.org
        env:
          SSH_KEY: ${{ secrets.SSH_KEY_MAXAMMANN_ORG }}
        run: |
          echo "$SSH_KEY" > id_rsa
          chmod 600 id_rsa
          ssh -o StrictHostKeyChecking=no -i id_rsa max@maxammann.org "rm -f ~/public_html/mapr-docs/*"
          rsync -e "ssh -o StrictHostKeyChecking=no -i id_rsa" -r "book/." max@maxammann.org:~/public_html/mapr-docs/
