name: web

on: [ workflow_dispatch ]

jobs:
  build-wasm-webgl:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
        working-directory: web
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            ~/.cargo/.crates*
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Install just
        run: cargo install just
      - name: Build
        run: just webpack-webgl-production
